services:
  - type: web
    name: simple-chat
    runtime: php
    buildCommand: composer install --no-dev
    startCommand: php -S 0.0.0.0:8000 -t public
    healthCheckPath: /
    envVars:
      - key: APP_KEY
        generateValue: true
