services:
  - type: web
    name: simple-chat
    runtime: php
    buildCommand: bundle install
    startCommand: php -S 0.0.0.0:8000 -t .
    healthCheckPath: /
    envVars:
      - key: APP_KEY
        generateValue: true